apiVersion: v2
name: opentelemetry-operator
version: 0.1.0
description: OpenTelemetry Operator Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-operator
maintainers:
  - name: bogdandrutu
  - name: dmitryax
  - name: pjanotti
  - name: tigrannajaryan
  - name: jpkrohling
  - name: alolita
  - name: Aneurysm9
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: "0.29.0"
