name: Lint and Test Charts

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
          if [[ "$changed" == *"opentelemetry-operator"* ]]; then
            echo "::set-output name=operator-changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch main

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.4.0/cert-manager.yaml
          kubectl wait --timeout=5m --for=condition=available deployment cert-manager -n cert-manager
          kubectl wait --timeout=5m --for=condition=available deployment cert-manager-webhook -n cert-manager
        if: steps.list-changed.outputs.operator-changed == 'true'

      - name: Install KUTTL
        run: |
          sudo curl -Lo /usr/local/bin/kubectl-kuttl https://github.com/kudobuilder/kuttl/releases/download/v0.11.0/kubectl-kuttl_0.11.0_linux_x86_64
          sudo chmod +x /usr/local/bin/kubectl-kuttl
          export PATH=$PATH:/usr/local/bin
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo update
          sleep 5s
          helm install my-opentelemetry-operator open-telemetry/opentelemetry-operator
          git clone https://github.com/open-telemetry/opentelemetry-operator.git
          kubectl kuttl test ./opentelemetry-operator/tests/e2e --config $GITHUB_WORKSPACE/charts/opentelemetry-operator/release/kuttl-test.yaml

      - name: Run KUTTL smoke tests
        run: |
          kubectl kuttl version
          git clone https://github.com/open-telemetry/opentelemetry-operator.git
          cd ./opentelemetry-operator
          kubectl kuttl test ./tests/e2e
